version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: postgres15
    env_file:
      - .env
    ports:
      - 5432:5432 # 端口号映射
    volumes:
      - /data/database/postgres13/data:/var/lib/postgresql/data # 数据持久化
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: postgres_network
